// src/js/constants/action-types.js

export const SELECT_DOCTOR = 'SELECT_DOCTOR';
export const SELECT_EPISODE = 'SELECT_EPISODE';
export const REQUEST_INTERACTIONS_DOCTOR = 'REQUEST_INTERACTIONS_DOCTOR';
export const REQUEST_INTERACTIONS_EPISODE = 'REQUEST_INTERACTIONS_EPISODE';
export const RECEIVE_INTERACTIONS_DOCTOR = 'RECEIVE_INTERACTIONS_DOCTOR';
export const RECEIVE_INTERACTIONS_EPISODE = 'RECEIVE_INTERACTIONS_EPISODE';
